const fs = require('fs');

const data = `[
  {"id":101,"slug":"aurora-brass-cooktop","name":"Aurora Brass Cooktop","category":"Cooktops","price":349,"compareAtPrice":429,"rating":4.8,"reviewCount":128,"badge":"Best Seller","featured":true,"isNew":false,"description":"A dual-burner cooktop designed for open kitchens, with warm brass details and a clean low-profile silhouette.","highlights":["Dual high-output brass burners","Toughened glass top with beveled edge","Low-profile metal control knobs","Quick-wipe spill channel"],"images":["/images/Gas1.jpg","/images/Induction2.webp","/images/Kettle45.webp"],"variantGroups":[{"name":"finish","label":"Finish","options":["Stone Ivory","Matte Black","Brushed Steel"]},{"name":"size","label":"Size","options":["Compact","Standard"]}],"specs":{"Burners":"2 brass burners","Surface":"Tempered glass","Warranty":"2 years"}},
  {"id":102,"slug":"slate-induction-hob","name":"Slate Induction Hob","category":"Cooktops","price":289,"compareAtPrice":369,"rating":4.7,"reviewCount":96,"badge":"Fast Heat","featured":true,"isNew":true,"description":"A minimal induction hob with responsive touch controls, quiet performance, and a matte slate finish.","highlights":["Instant induction response","Touch slider with child lock","Auto-pan detection","Slim countertop profile"],"images":["/images/Induction2.webp","/images/Gas1.jpg","/images/Microwave16.webp"],"variantGroups":[{"name":"finish","label":"Finish","options":["Slate","Pearl","Carbon"]},{"name":"zone","label":"Cooking Zone","options":["Single Zone","Dual Zone"]}],"specs":{"Power":"1800W","Controls":"Touch slider","Warranty":"2 years"}},
  {"id":103,"slug":"forge-carbon-skillet","name":"Forge Carbon Skillet","category":"Cookware","price":84,"compareAtPrice":108,"rating":4.9,"reviewCount":212,"badge":"Chef Pick","featured":true,"isNew":false,"description":"Balanced carbon-steel cookware that sears like cast iron but feels lighter in hand for everyday service.","highlights":["Pre-seasoned carbon steel","Fast and even heat response","Stainless helper handle","Oven safe up to 600F"],"images":["/images/Pan4.webp","/images/Kadai5.webp","/images/Tawa7.webp"],"variantGroups":[{"name":"size","label":"Size","options":["10 in","12 in","14 in"]},{"name":"finish","label":"Handle","options":["Brushed Steel","Walnut","Matte Black"]}],"specs":{"Material":"Carbon steel","Weight":"1.6 lb","Warranty":"Lifetime"}},
  {"id":104,"slug":"contour-pressure-cooker","name":"Contour Pressure Cooker","category":"Cookware","price":119,"compareAtPrice":149,"rating":4.6,"reviewCount":87,"badge":"Everyday Essential","featured":false,"isNew":false,"description":"A polished steel pressure cooker with secure locking, steady pressure control, and a compact footprint.","highlights":["Thick tri-ply base","Cool-touch handle geometry","Precision pressure valve","Dishwasher-safe body"],"images":["/images/Cooker3.jpg","/images/Pan6.webp","/images/Plate20.webp"],"variantGroups":[{"name":"capacity","label":"Capacity","options":["3 qt","5 qt","7 qt"]},{"name":"finish","label":"Finish","options":["Polished Steel","Graphite"]}],"specs":{"Material":"Stainless steel","Base":"Tri-ply","Warranty":"5 years"}},
  {"id":105,"slug":"atelier-mixer-grinder","name":"Atelier Mixer Grinder","category":"Appliances","price":249,"compareAtPrice":329,"rating":4.8,"reviewCount":144,"badge":"Editor's Pick","featured":true,"isNew":false,"description":"A high-torque prep station built for sauces, spice work, and morning blends, wrapped in a calm satin finish.","highlights":["900W copper motor","Three jar sizes included","Low-vibration base","Pulse and smart-speed modes"],"images":["/images/Mixer Griender13.webp","/images/Juicer14.webp","/images/Whish42.webp"],"variantGroups":[{"name":"finish","label":"Finish","options":["Satin White","Forest","Ink"]},{"name":"bundle","label":"Bundle","options":["Core Set","Prep Set"]}],"specs":{"Motor":"900W","Capacity":"3 jars","Warranty":"3 years"}},
  {"id":106,"slug":"studio-two-slice-toaster","name":"Studio Two-Slice Toaster","category":"Appliances","price":79,"compareAtPrice":99,"rating":4.4,"reviewCount":58,"badge":"Morning Upgrade","featured":false,"isNew":true,"description":"A compact toaster with clean lines, precise browning, and quiet operation for smaller kitchen counters.","highlights":["Six shade settings","Lift-and-look toast control","Removable crumb tray","Compact counter footprint"],"images":["/images/Toaster15.webp","/images/Kettle45.webp","/images/Cup23.webp"],"variantGroups":[{"name":"finish","label":"Finish","options":["Cream","Graphite","Sand"]},{"name":"voltage","label":"Voltage","options":["110V","220V"]}],"specs":{"Slots":"2 wide slots","Power":"850W","Warranty":"2 years"}},
  {"id":107,"slug":"ember-electric-kettle","name":"Ember Electric Kettle","category":"Appliances","price":69,"compareAtPrice":89,"rating":4.7,"reviewCount":73,"badge":"New Arrival","featured":true,"isNew":true,"description":"A fast-boil kettle with a soft-touch handle, hold-warm function, and a silhouette that disappears into the counter.","highlights":["Fast-boil concealed element","Keep-warm for 30 minutes","Soft-touch grip","Cordless 360 base"],"images":["/images/Kettle45.webp","/images/Cup23.webp","/images/Glass22.webp"],"variantGroups":[{"name":"finish","label":"Finish","options":["Pearl","Matte Black","Pine"]},{"name":"capacity","label":"Capacity","options":["1.2 L","1.7 L"]}],"specs":{"Capacity":"1.7 liters","Power":"1500W","Warranty":"2 years"}},
  {"id":108,"slug":"horizon-water-filter","name":"Horizon Water Filter","category":"Appliances","price":159,"compareAtPrice":199,"rating":4.5,"reviewCount":64,"badge":"Healthy Home","featured":false,"isNew":false,"description":"Counter-ready filtration with a quiet flow, compact cartridge housing, and materials selected for daily use.","highlights":["Multi-stage filtration","Slim countertop profile","Quick cartridge swap","BPA-free storage tank"],"images":["/images/Water Filter19.webp","/images/Storage48.webp","/images/Glass22.webp"],"variantGroups":[{"name":"finish","label":"Finish","options":["Cloud","Mist","Charcoal"]},{"name":"kit","label":"Replacement Kit","options":["Starter Kit","12-Month Kit"]}],"specs":{"Filtration":"4-stage","Flow rate":"2 L/hr","Warranty":"18 months"}},
  {"id":109,"slug":"stack-airtight-canister-set","name":"Stack Airtight Canister Set","category":"Storage","price":92,"compareAtPrice":118,"rating":4.6,"reviewCount":111,"badge":"Pantry Favorite","featured":true,"isNew":false,"description":"A modular storage set with tactile lids, low-visual clutter, and stack-friendly proportions for modern pantries.","highlights":["Four nesting sizes","Silicone airtight seals","Clear body with smoke lid","Label-ready front face"],"images":["/images/Storage48.webp","/images/Lunch box30.webp","/images/Measuring cup38.webp"],"variantGroups":[{"name":"set","label":"Set","options":["4 Piece","6 Piece","8 Piece"]},{"name":"lid","label":"Lid Color","options":["Smoke","Sand","Forest"]}],"specs":{"Pieces":"4 canisters","Material":"Food-safe polymer","Warranty":"1 year"}},
  {"id":110,"slug":"oak-rolling-board-kit","name":"Oak Rolling Board Kit","category":"Tools","price":54,"compareAtPrice":70,"rating":4.3,"reviewCount":41,"badge":"Handcrafted","featured":false,"isNew":false,"description":"An heirloom-inspired board and rolling pin kit shaped from smooth hardwood for clean prep and warm display.","highlights":["Solid wood board and pin","Oil-finished natural grain","Balanced hand feel","Hang-ready profile"],"images":["/images/Chockla29.webp","/images/Belna28.webp","/images/Measuring spoon39.webp"],"variantGroups":[{"name":"wood","label":"Wood Finish","options":["Natural Oak","Walnut","Ash"]},{"name":"size","label":"Board Size","options":["Small","Standard"]}],"specs":{"Material":"Seasoned hardwood","Care":"Hand wash only","Warranty":"1 year"}},
  {"id":111,"slug":"brushed-ladle-serve-set","name":"Brushed Ladle Serve Set","category":"Dining","price":48,"compareAtPrice":62,"rating":4.5,"reviewCount":52,"badge":"Table Ready","featured":false,"isNew":false,"description":"A serving set with smooth edges, matte handles, and durable steel construction for daily hosting.","highlights":["Serving spoon, ladle, and fork","Brushed stainless finish","Dishwasher safe","Weighted for comfortable serving"],"images":["/images/Serving spoon27.webp","/images/Ladle8.webp","/images/Fork25.webp"],"variantGroups":[{"name":"finish","label":"Finish","options":["Silver","Champagne","Onyx"]},{"name":"set","label":"Set Size","options":["3 Piece","5 Piece"]}],"specs":{"Material":"18/10 stainless steel","Pieces":"3 serving tools","Warranty":"2 years"}},
  {"id":112,"slug":"linen-hosting-bundle","name":"Linen Hosting Bundle","category":"Accessories","price":67,"compareAtPrice":84,"rating":4.4,"reviewCount":38,"badge":"Soft Launch","featured":false,"isNew":true,"description":"A soft-touch bundle for gifting or hosting, pairing absorbent linens with a tailored apron and clean neutral palette.","highlights":["Washed cotton apron","Two absorbent kitchen towels","Gift-ready folded presentation","Machine washable finish"],"images":["/images/Apron37.webp","/images/Kitchen towel36.webp","/images/Trivet46.webp"],"variantGroups":[{"name":"color","label":"Color","options":["Oat","Moss","Ink"]},{"name":"bundle","label":"Bundle","options":["Host Set","Gift Set"]}],"specs":{"Fabric":"Washed cotton","Pieces":"3","Warranty":"6 months"}},
  {"id":113,"slug":"bottle-opener","name":"Bottle Opener","category":"Tools","price":19,"compareAtPrice":25,"rating":4.5,"reviewCount":43,"badge":"New Arrival","featured":false,"isNew":true,"description":"Heavy duty bottle opener.","highlights":["Steel construction","Ergonomic","Hanging hole"],"images":["/images/Bottle opener44.webp"],"variantGroups":[{"name":"finish","label":"Finish","options":["Chrome","Matte"]}],"specs":{"Material":"Steel","Warranty":"Lifetime"}},
  {"id":114,"slug":"bowl","name":"Serving Bowl","category":"Cookware","price":28,"compareAtPrice":36,"rating":4.7,"reviewCount":109,"badge":"Best Seller","featured":true,"isNew":false,"description":"Elegant serving bowl.","highlights":["Ceramic","Microwave safe","Beautiful glaze"],"images":["/images/Bowl21.webp"],"variantGroups":[{"name":"size","label":"Size","options":["Medium","Large"]}],"specs":{"Material":"Ceramic","Capacity":"1.5L"}},
  {"id":115,"slug":"butter-knife","name":"Butter Knife","category":"Dining","price":17,"compareAtPrice":23,"rating":4.6,"reviewCount":65,"badge":"Table Ready","featured":false,"isNew":true,"description":"Perfect for butter spreading.","highlights":["Stainless steel","Wood handle","Balanced"],"images":["/images/Butter knife26.webp"],"variantGroups":[{"name":"handle","label":"Handle","options":["Wood","Plastic"]}],"specs":{"Length":"5in","Material":"Stainless"}},
  {"id":116,"slug":"channi","name":"Channi","category":"Tools","price":22,"compareAtPrice":28,"rating":4.5,"reviewCount":82,"badge":"Everyday Essential","featured":false,"isNew":false,"description":"Frying strainer.","highlights":["Flat mesh","Long handle","Heat resistant"],"images":["/images/Channi47.webp"],"variantGroups":[{"name":"size","label":"Size","options":["Small","Large"]}],"specs":{"Material":"Steel","Warranty":"1 year"}},
  {"id":117,"slug":"chockla","name":"Chockla","category":"Tools","price":38,"compareAtPrice":49,"rating":4.8,"reviewCount":123,"badge":"Chef Pick","featured":true,"isNew":false,"description":"Wooden mortar.","highlights":["Seasoned wood","Heavy base","Traditional"],"images":["/images/Chockla29.webp"],"variantGroups":[{"name":"size","label":"Size","options":["Small","Large"]}],"specs":{"Material":"Wood","Warranty":"Lifetime"}},
  {"id":118,"slug":"chopping-board","name":"Chopping Board","category":"Tools","price":44,"compareAtPrice":57,"rating":4.6,"reviewCount":95,"badge":"Handcrafted","featured":false,"isNew":true,"description":"Premium chopping board.","highlights":["Juice groove","Non-slip","Easy clean"],"images":["/images/Chopping board10.webp"],"variantGroups":[{"name":"material","label":"Material","options":["Bamboo","Plastic"]}],"specs":{"Size":"12x18in","Thickness":"0.5in"}},
  {"id":119,"slug":"colander","name":"Colander","category":"Cookware","price":31,"compareAtPrice":40,"rating":4.5,"reviewCount":71,"badge":"Best Seller","featured":false,"isNew":false,"description":"Pasta colander.","highlights":["Perforated","Handles","Stackable"],"images":["/images/Colander40.webp"],"variantGroups":[{"name":"size","label":"Size","options":["Small","Large"]}],"specs":{"Material":"Plastic","Capacity":"3L"}},
  {"id":120,"slug":"dish-rack","name":"Dish Rack","category":"Storage","price":62,"compareAtPrice":80,"rating":4.4,"reviewCount":88,"badge":"Pantry Favorite","featured":true,"isNew":true,"description":"Countertop dish rack.","highlights":["Adjustable","Drainboard","Rustproof"],"images":["/images/Dish rack31.webp"],"variantGroups":[{"name":"size","label":"Size","options":["Compact","Full"]}],"specs":{"Material":"Steel","Warranty":"2 years"}},
  {"id":121,"slug":"dish-soap","name":"Dish Soap","category":"Accessories","price":11,"compareAtPrice":15,"rating":4.9,"reviewCount":456,"badge":"Everyday Essential","featured":false,"isNew":false,"description":"Premium dish soap.","highlights":["Natural ingredients","Long lasting","Foamy"],"images":["/images/Dish soap35.jpg"],"variantGroups":[{"name":"scent","label":"Scent","options":["Citrus","Lavender"]}],"specs":{"Volume":"500ml","Type":"Liquid"}},
  {"id":122,"slug":"dish-sponge","name":"Dish Sponge","category":"Accessories","price":7,"compareAtPrice":10,"rating":4.7,"reviewCount":289,"badge":"Best Seller","featured":false,"isNew":true,"description":"Heavy duty sponge.","highlights":["Scrubber side","Soft side","Anti-bacterial"],"images":["/images/Dish sponge34.webp"],"variantGroups":[{"name":"pack","label":"Pack","options":["Single","3 Pack"]}],"specs":{"Size":"Standard","Durability":"High"}},
  {"id":123,"slug":"fork","name":"Dinner Fork","category":"Dining","price":21,"compareAtPrice":27,"rating":4.6,"reviewCount":76,"badge":"Table Ready","featured":false,"isNew":false,"description":"Classic dinner fork.","highlights":["18/10 stainless","Ergonomic","Polished"],"images":["/images/Fork25.webp"],"variantGroups":[{"name":"finish","label":"Finish","options":["Mirror","Matte"]}],"specs":{"Length":"8in","Weight":"Light"}},
  {"id":124,"slug":"glass","name":"Tumbler Glass","category":"Dining","price":23,"compareAtPrice":30,"rating":4.5,"reviewCount":112,"badge":"Everyday Essential","featured":true,"isNew":true,"description":"Durable drinking glass.","highlights":["Tempered","Dishwasher safe","Chip resistant"],"images":["/images/Glass22.webp"],"variantGroups":[{"name":"size","label":"Size","options":["Short","Tall"]}],"specs":{"Capacity":"400ml","Material":"Glass"}},
  {"id":125,"slug":"grater","name":"Box Grater","category":"Tools","price":27,"compareAtPrice":35,"rating":4.7,"reviewCount":167,"badge":"Chef Pick","featured":false,"isNew":false,"description":"4-sided box grater.","highlights":["Stainless blades","Non-slip feet","Handle","Container"],"images":["/images/Grater12.webp"],"variantGroups":[{"name":"size","label":"Size","options":["Small","Large"]}],"specs":{"Blades":"4 sides","Material":"Stainless"}},
  {"id":126,"slug":"knife","name":"Chef Knife","category":"Tools","price":89,"compareAtPrice":115,"rating":4.8,"reviewCount":234,"badge":"Best Seller","featured":true,"isNew":false,"description":"Professional chef knife.","highlights":["Full tang","Ergonomic handle","Sharp edge"],"images":["/images/Knife9.webp"],"variantGroups":[{"name":"length","label":"Length","options":["8in","10in"]}],"specs":{"Blade":"German steel","Hardness":"58 HRC"}},
  {"id":127,"slug":"ladle","name":"Serving Ladle","category":"Dining","price":25,"compareAtPrice":32,"rating":4.6,"reviewCount":89,"badge":"Table Ready","featured":false,"isNew":true,"description":"Long handle ladle.","highlights":["Stainless","Pour spout","Hanging loop"],"images":["/images/Ladle8.webp"],"variantGroups":[{"name":"length","label":"Length","options":["12in","14in"]}],"specs":{"Material":"Stainless","Capacity":"4oz"}},
  {"id":128,"slug":"lunch-box","name":"Lunch Box","category":"Storage","price":39,"compareAtPrice":50,"rating":4.5,"reviewCount":156,"badge":"Pantry Favorite","featured":false,"isNew":false,"description":"Leak proof lunch box.","highlights":["BPA free","Microwave safe","Compartments"],"images":["/images/Lunch box30.webp"],"variantGroups":[{"name":"size","label":"Size","options":["1 Compartment","3 Compartments"]}],"specs":{"Material":"Plastic","Volume":"1L"}},
  {"id":129,"slug":"measuring-cup","name":"Measuring Cup Set","category":"Tools","price":18,"compareAtPrice":24,"rating":4.7,"reviewCount":198,"badge":"Everyday Essential","featured":false,"isNew":true,"description":"Plastic measuring cups.","highlights":["Stackable","BPA free","Clear markings"],"images":["/images/Measuring cup38.webp"],"variantGroups":[{"name":"set","label":"Set","options":["4pc","6pc"]}],"specs":{"Sizes":"1/4-1 cup","Material":"Plastic"}},
  {"id":130,"slug":"measuring-spoon","name":"Measuring Spoon Set","category":"Tools","price":15,"compareAtPrice":20,"rating":4.6,"reviewCount":143,"badge":"Best Seller","featured":true,"isNew":false,"description":"Stainless measuring spoons.","highlights":["Magnetic","Stackable","Double sided"],"images":["/images/Measuring spoon39.webp"],"variantGroups":[{"name":"material","label":"Material","options":["Plastic","Stainless"]}],"specs":{"Sizes":"1/4 tsp-1 tbsp","Count":"6pc"}},
  {"id":131,"slug":"oven","name":"Countertop Oven","category":"Appliances","price":199,"compareAtPrice":249,"rating":4.5,"reviewCount":67,"badge":"Morning Upgrade","featured":false,"isNew":true,"description":"Compact convection oven.","highlights":["Convection fan","Multiple modes","Easy clean"],"images":["/images/Oven17.webp"],"variantGroups":[{"name":"size","label":"Size","options":["Compact","Standard"]}],"specs":{"Power":"1200W","Capacity":"20L"}},
  {"id":132,"slug":"peeler","name":"Y Peeler","category":"Tools","price":12,"compareAtPrice":17,"rating":4.8,"reviewCount":289,"badge":"Chef Pick","featured":false,"isNew":false,"description":"Swivel blade peeler.","highlights":["Sharp stainless blade","Ergonomic","Eye remover"],"images":["/images/Peeler11.webp"],"variantGroups":[{"name":"color","label":"Color","options":["Green","Red"]}],"specs":{"Blade":"Japanese steel","Handle":"Rubberized"}},
  {"id":133,"slug":"refrigerator","name":"Mini Refrigerator","category":"Appliances","price":299,"compareAtPrice":379,"rating":4.4,"reviewCount":54,"badge":"Healthy Home","featured":true,"isNew":true,"description":"Compact mini fridge.","highlights":["Low noise","Energy efficient","Adjustable shelves"],"images":["/images/Refrigerator18.webp"],"variantGroups":[{"name":"color","label":"Color","options":["White","Black"]}],"specs":{"Capacity":"90L","Power":"80W"}},
  {"id":134,"slug":"salad-spinner","name":"Salad Spinner","category":"Appliances","price":34,"compareAtPrice":44,"rating":4.6,"reviewCount":112,"badge":"Everyday Essential","featured":false,"isNew":false,"description":"High speed salad spinner.","highlights":["Push button","Bowl doubles as container","Stackable"],"images":["/images/Salad spin49.webp"],"variantGroups":[{"name":"size","label":"Size","options":["Small","Large"]}],"specs":{"Capacity":"4L","Material":"Plastic"}},
  {"id":135,"slug":"sink","name":"Kitchen Sink","category":"Appliances","price":189,"compareAtPrice":239,"rating":4.5,"reviewCount":45,"badge":"New Arrival","featured":false,"isNew":true,"description":"Stainless kitchen sink.","highlights":["Double basin","Noise reduction","Overflow protection"],"images":["/images/Sink32.webp"],"variantGroups":[{"name":"mount","label":"Mount","options":["Undermount","Drop in"]}],"specs":{"Material":"Stainless 304","Size":"33in"}},
  {"id":136,"slug":"spoon","name":"Serving Spoon","category":"Dining","price":19,"compareAtPrice":25,"rating":4.6,"reviewCount":78,"badge":"Table Ready","featured":false,"isNew":false,"description":"Solid serving spoon.","highlights":["Stainless","Long handle","Polished"],"images":["/images/Spoon24.webp"],"variantGroups":[{"name":"length","label":"Length","options":["10in","12in"]}],"specs":{"Material":"18/8","Weight":"Light"}},
  {"id":137,"slug":"stainer","name":"Oil Stainer","category":"Cookware","price":29,"compareAtPrice":37,"rating":4.7,"reviewCount":94,"badge":"Best Seller","featured":true,"isNew":true,"description":"Fine mesh stainer.","highlights":["Silicone handle","Fine mesh","Hang dry"],"images":["/images/Stainer41.webp"],"variantGroups":[{"name":"size","label":"Size","options":["Small","Medium"]}],"specs":{"Mesh":"Fine","Handle":"Heat resistant"}},
  {"id":138,"slug":"tap-pipe","name":"Tap Pipe","category":"Appliances","price":79,"compareAtPrice":99,"rating":4.5,"reviewCount":56,"badge":"Healthy Home","featured":false,"isNew":false,"description":"Pull out kitchen tap.","highlights":["Spray mode","Swivel spout","Easy install"],"images":["/images/Tap pipe33.webp"],"variantGroups":[{"name":"finish","label":"Finish","options":["Chrome","Brushed"]}],"specs":{"Flow":"2.2gpm","Type":"Pull out"}},
  {"id":139,"slug":"tongs","name":"Kitchen Tongs","category":"Tools","price":23,"compareAtPrice":30,"rating":4.6,"reviewCount":167,"badge":"Everyday Essential","featured":false,"isNew":true,"description":"Locking kitchen tongs.","highlights":["Stainless","Lock feature","Heat resistant"],"images":["/images/Tongs43.webp"],"variantGroups":[{"name":"length","label":"Length","options":["9in","12in"]}],"specs":{"Material":"Stainless","Max temp":"500F"}},
  {"id":140,"slug":"trivet","name":"Silicone Trivet","category":"Accessories","price":16,"compareAtPrice":21,"rating":4.7,"reviewCount":134,"badge":"Best Seller","featured":false,"isNew":false,"description":"Heat resistant trivet.","highlights":["Silicone","Foldable","Non slip"],"images":["/images/Trivet46.webp"],"variantGroups":[{"name":"shape","label":"Shape","options":["Round","Square"]}],"specs":{"Max temp":"450F","Material":"Silicone"}}
]`;

try {
  fs.writeFileSync('src/data/products.json', data);
  console.log("Successfully restored products.json via Node script bypass!");
} catch (e) {
  console.error("Failed to write products.json:", e);
}
